### ISSUE TITLE
Truncates more lines than intended on smaller viewports

### ISSUE THREAD

**Issue by skoldborg** [yuanqing/line-clamp#12]
I have an issue where any text that apply line-clamp to gets truncated to just one line in smaller (< 968px) viewports even though I've set it the option to three lines. Works fine for viewports > 968px. Any ideas what could be causing this?

I've confirmed that the line-clamp method correctly calculates the line-height of the text element.

**Comment by yuanqing** [comment]
@skoldborg Thanks for reporting this. However it is a bit hard to figure out the problem without having a small and scoped down reproduction of the issue eg. a CodePen

**Comment by skoldborg** [comment]
@yuanqing Of course. Turns out it was an issue with a masonry implementation. Thanks for your response, I'll close the issue now.
