### ISSUE TITLE
The codepen is broken

### ISSUE THREAD

**Issue by adriaandotcom** [yuanqing/line-clamp#7]
The code pen (https://codepen.io/lyuanqing/pen/VQQVry) is broken:

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/1079135/48714523-8ab21980-ec1b-11e8-8c90-ab15ab1577c8.png">

> Uncaught ReferenceError: lineClamp is not defined at pen.js:2 (anonymous) @ pen.js:2

https://wzrd.in/standalone/line-clamp@latest returns a 504 Gateway Time-out

**Comment by johnhunter** [comment]
Cloning the repo, running `npm i` and `npm start`. I found 
```"lineClamp is not defined"```
Seems the script src did not load.

Fix was to use a relative path
```html
<script src="./bundle.js"></script>
```

**Comment by yuanqing** [comment]
Have edited the CodePen to use [bundle.run](bundle.run) instead, and it seems to work now
